###
GET http://localhost:3001/api/persons

###
GET http://localhost:3001/api/persons/62fa683f5f1b6543a3e1b523

###
DELETE http://localhost:3001/api/persons/62fa683f5f1b6543a3e1b523

###
POST http://localhost:3001/api/persons
content-type: application/json

{
  "name": "Paul Ehrenfest",
  "number": "137-2333454"
}